### ISSUE TITLE
StakingPool.requestAllocation() unit tests

### ISSUE THREAD

**Issue by kyledewy** [NexusMutual/smart-contracts#582] opened 2022-12-20 18:52 UTC
Unit tests have been started, mostly focusing on premium + pricing in this PR: https://github.com/NexusMutual/smart-contracts/pull/543

`requestAllocation()` is complex and should include tests verifying other aspects of it's functionality like `updateStoredAllocations` and `rewards` & `rewardsPerSecond`. 
Some of the pricing tests can be removed as well, as they are redundantly tested in `StakingPool.calculatePremium.js`

**Comment by roxdanila** [comment] 2023-01-03 09:12
Duplicate of #492

**Closed by roxdanila** 2023-01-03 09:12 UTC
